-- HU-9: tickets de lectores con más categorías, código legible y adjunto opcional.
-- Las migraciones se ejecutan en cada arranque, por eso cada sentencia es idempotente.

ALTER TABLE alert_ticket_service.tickets
    DROP CONSTRAINT IF EXISTS chk_ticket_category;

ALTER TABLE alert_ticket_service.tickets
    ADD CONSTRAINT chk_ticket_category CHECK (category IN (
        'carcasa_rota',
        'tapa_faltante',
        'etiqueta_ilegible',
        'deterioro_estetico',
        'cable_deteriorado',
        'conector_suelto',
        'pantalla_danada',
        'suciedad_acumulada',
        'otro'
    ));

-- Número correlativo para mostrar códigos como TK-2026-000123 sin exponer el UUID.
ALTER TABLE alert_ticket_service.tickets
    ADD COLUMN IF NOT EXISTS ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tickets_ticket_number
    ON alert_ticket_service.tickets(ticket_number);

-- Adjunto opcional del ticket. El archivo vive en el volumen del alert-ticket-service;
-- PostgreSQL conserva únicamente los metadatos.
CREATE TABLE IF NOT EXISTS alert_ticket_service.ticket_attachments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID NOT NULL UNIQUE REFERENCES alert_ticket_service.tickets(id) ON DELETE CASCADE,
    storage_name VARCHAR(160) NOT NULL UNIQUE,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(80) NOT NULL,
    size_bytes INTEGER NOT NULL,
    uploaded_by_user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_ticket_attachment_size CHECK (size_bytes > 0 AND size_bytes <= 5242880),
    CONSTRAINT chk_ticket_attachment_type CHECK (content_type IN ('application/pdf', 'image/jpeg', 'image/png'))
);
